sudo: required
language: groovy
jdk:
  - oraclejdk8
services:
  - docker
env:
  COMPOSE_VERSION: 1.9.0
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - chmod +x gradlew
