app:
  build: .
  ports:
    - 8080:8080
  links:
    - db
  environment:
    JAVA_OPTS: -Xmx128m
db:
  image: postgres:9.5.5
  ports:
    - 5432:5432
  volumes_from:
    - dbdata
  mem_limit: 300m
  environment:
    LC_ALL: C.UTF-8
    POSTGRES_USER: tvarkauvilniu
    POSTGRES_PASSWORD: tvarkauvilniu
    POSTGRES_DB: tvarkauvilniu
dbdata:
  image: busybox
  volumes:
  - /var/lib/postgresql
