version: '2'

services:
  app:
    build: .
    links:
      - db
    environment:
      TVARKAU_VILNIU_RAILS_DB_HOST: db
      TVARKAU_VILNIU_RAILS_DB_PORT: 5432
  db:
    image: postgres:9.5.6
    mem_limit: 300m
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: vilnius
      POSTGRES_PASSWORD: vilnius
